services:
  - type: web
    name: moda-elegante-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      # Configura estas variables en el dashboard de Render:
      # MONGO_URI, JWT_SECRET, CORS_ORIGIN, FRONTEND_URL
      # CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
      # SENDGRID_API_KEY, STRIPE_SECRET_KEY, etc.
