export const TEST_PRODUCTS = [
  {
    name: 'Classic White T-Shirt',
    description: 'A comfortable and versatile white t-shirt made from 100% organic cotton. Perfect for everyday wear.',
    price: 29.99,
    sku: 'TS-WHT-001',
    category: 'shirts',
    gender: 'unisex',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['white', 'black', 'gray'],
    images: ['/products/white-tshirt-1.jpg', '/products/white-tshirt-2.jpg'],
    stock: 150,
    tags: ['basic', 'cotton', 'casual'],
    brand: 'Fashion Store',
    material: '100% Organic Cotton',
    rating: 4.5,
    reviewCount: 89,
  },
  {
    name: 'Slim Fit Jeans',
    description: 'Modern slim fit jeans with stretch fabric for comfort and style. Perfect for both casual and semi-formal occasions.',
    price: 79.99,
    discountPrice: 59.99,
    sku: 'JN-SLM-002',
    category: 'pants',
    gender: 'men',
    availableSizes: ['S', 'M', 'L', 'XL'],
    colors: ['blue', 'black', 'gray'],
    images: ['/products/slim-jeans-1.jpg', '/products/slim-jeans-2.jpg'],
    stock: 75,
    tags: ['denim', 'slim-fit', 'stretch'],
    brand: 'Levi\'s',
    material: '98% Cotton, 2% Elastane',
    rating: 4.3,
    reviewCount: 156,
  },
  {
    name: 'Floral Summer Dress',
    description: 'Beautiful floral print dress perfect for summer occasions. Lightweight and breathable fabric.',
    price: 89.99,
    sku: 'DR-FLR-003',
    category: 'dresses',
    gender: 'women',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['pink', 'blue', 'yellow'],
    images: ['/products/floral-dress-1.jpg', '/products/floral-dress-2.jpg'],
    stock: 45,
    tags: ['floral', 'summer', 'casual'],
    brand: 'Zara',
    material: '100% Viscose',
    rating: 4.7,
    reviewCount: 203,
  },
  {
    name: 'Leather Sneakers',
    description: 'Premium leather sneakers with comfortable cushioning. Perfect for everyday wear and light activities.',
    price: 129.99,
    discountPrice: 99.99,
    sku: 'SH-SNK-004',
    category: 'shoes',
    gender: 'unisex',
    availableSizes: ['S', 'M', 'L', 'XL'],
    colors: ['white', 'black', 'brown'],
    images: ['/products/leather-sneakers-1.jpg', '/products/leather-sneakers-2.jpg'],
    stock: 60,
    tags: ['leather', 'comfortable', 'casual'],
    brand: 'Nike',
    material: 'Genuine Leather',
    rating: 4.4,
    reviewCount: 127,
  },
  {
    name: 'Designer Handbag',
    description: 'Elegant designer handbag with multiple compartments. Perfect for work or special occasions.',
    price: 199.99,
    sku: 'AC-BAG-005',
    category: 'accessories',
    gender: 'women',
    availableSizes: ['M'],
    colors: ['black', 'brown', 'red'],
    images: ['/products/designer-bag-1.jpg', '/products/designer-bag-2.jpg'],
    stock: 25,
    tags: ['designer', 'elegant', 'work'],
    brand: 'Calvin Klein',
    material: 'Genuine Leather',
    rating: 4.8,
    reviewCount: 94,
  },
  {
    name: 'Winter Jacket',
    description: 'Warm and stylish winter jacket with water-resistant coating. Perfect for cold weather.',
    price: 159.99,
    discountPrice: 119.99,
    sku: 'JK-WNT-006',
    category: 'jackets',
    gender: 'men',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['black', 'blue', 'green'],
    images: ['/products/winter-jacket-1.jpg', '/products/winter-jacket-2.jpg'],
    stock: 35,
    tags: ['winter', 'warm', 'water-resistant'],
    brand: 'The North Face',
    material: 'Polyester with Down Fill',
    rating: 4.6,
    reviewCount: 178,
  },
  {
    name: 'Silk Blouse',
    description: 'Elegant silk blouse perfect for professional settings. Soft and comfortable with a luxurious feel.',
    price: 119.99,
    sku: 'BL-SLK-007',
    category: 'shirts',
    gender: 'women',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['white', 'black', 'pink'],
    images: ['/products/silk-blouse-1.jpg', '/products/silk-blouse-2.jpg'],
    stock: 40,
    tags: ['silk', 'professional', 'elegant'],
    brand: 'H&M',
    material: '100% Silk',
    rating: 4.5,
    reviewCount: 112,
  },
  {
    name: 'Sports Shorts',
    description: 'Comfortable sports shorts with moisture-wicking fabric. Perfect for workouts and outdoor activities.',
    price: 39.99,
    sku: 'SH-SPT-008',
    category: 'pants',
    gender: 'unisex',
    availableSizes: ['S', 'M', 'L', 'XL'],
    colors: ['black', 'blue', 'red'],
    images: ['/products/sports-shorts-1.jpg', '/products/sports-shorts-2.jpg'],
    stock: 80,
    tags: ['sports', 'moisture-wicking', 'comfortable'],
    brand: 'Adidas',
    material: '100% Polyester',
    rating: 4.2,
    reviewCount: 145,
  },
];